//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatuesRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatueTable
    {
        public decimal Statue_number { get; set; }
        public string Character { get; set; }
        public string Company { get; set; }
        public string License { get; set; }
        public string Scale { get; set; }
        public decimal Edition_Size { get; set; }
    }
}
